### ISSUE TITLE
Error when modprobe the module rtl8192cu

### ISSUE THREAD

**Issue by cocconat** [pvaret/rtl8192cu-fixes#126]
Hi, thank you very much for this driver, I ve followed the README and everything looks fine except it s not working after reboot :/ 

So I tried to mount manually with 

> sudo  modprobe rtl8192cu

but it runs ointo this error:

> modprobe: ERROR: ../libkmod/libkmod-module.c:977 command_do() Error running install command for rtlwifi

> modprobe:  ERROR: could not insert 'rtl8192cu': Operation not permitted

any hint?

thank you

**Comment by pvaret** [comment]
"rtl8192cu" is the default driver that ships with the kernel. For this driver, you'll want "8192cu", without the "rtl" part. I think loading rtl8192cu fails because it needs rtlwifi as a dependency, and if you followed the installation instructions then you blacklisted that by installing the blacklist-native-rtl8192.conf file into /etc/modprobe.d.

That said, I would advise switching to the new rtl8xxxu driver from the mainline kernel. It works pretty well. (Don't forget to remove the blacklist mentioned above!) You may have to blacklist rtl8192cu, though, as it tends to be loaded by default, confusingly.
