### ISSUE TITLE
Can't able to detect rtl8192cu externel wifi adapter

### ISSUE THREAD

**Issue by spaul13** [pvaret/rtl8192cu-fixes#144]
I did all the steps for install the rtl8192cu on android (LineageOS on Pixel 2, kernel version- 4.x) mentioned in the README. Still it can't able to detect the externel 8192 usb wifi adapter. Although **lsusb** can list the name of the wifi adapter.

Can anyone please tell me where it seems to be faulty?

**Comment by pvaret** [comment]
LineageOS in Pixel 2? Oh man. I HOPE whoever makes that does not rely on this repo for their wifi? :) This repo is a pile of kludges to make an old vendor driver compile on recent kernels and each year I'm more amazed that it works at all. Please consider using the proper kernel driver (rtlxxxu) instead, and report any issues with it to the kernel maintainers, since that's how the situation will get better for everyone (and I'll finally be able to close this repo for good).

I'm going to close this ticket for now, as no one seems to have turned up with useful info for you. But please feel free to pipe in, anyone else using LineageOS on a Pixel 2 and having some insight to contribute.
