### ISSUE TITLE
WiFi random drops on RTL8723BE

### ISSUE THREAD

**Issue by Petahh** [pvaret/rtl8192cu-fixes#40]
Hello Guys,
I'm having problems with my WiFi on Fedora21. Connection drops randomly. I found interesting that this problem occurs more frequent when I'm utilizing my connection, like watching YouTube.
Internet is working and then suddenly everything disconnects and connection starts spinning. Only off/on on wifi adapter use to help, sometimes I end up with rebooting whole notebook. Router is perfectly fine as other devices like PS4, Macbook, Android are not experiencing any problems.

I'm running on ProBook 450 G2 which has below wireless adapter:

Realtek RTL8723BE PCIe Wireless Network Adapter
driver: rtl8723be
port: 3000
bus-ID: 09:00.0
IF: wlo1
state: up

I can see that you have already discovered this issue in Troubleshooting section with workaround, I also believe that patch is being developed, would it be possible to port to RTL8723BE ? This problem really drives me crazy an I believe also many of other RTL wireless users as it seems to be fairly global problem, so any help is highly appreciated. With kind regards Peter.

**Comment by pvaret** [comment]
Hi Petahh,

Okay, I've said it a lot, but I'll say it again. This here is a port of Realtek's own RTL8192cu driver to kernels 3.11 and above. (Realtek's driver use a deprecated API that was removed in recent kernels.) That's all it is. If Realtek's driver doesn't support a given piece of hardware, this driver won't support it either.

In order to port this driver to your hardware, I would need 1. to know if your hardware is similar enough to the RTL8192cu to share a common driver (I very much doubt it, as your hardware is PCI and this is a USB driver), 2. to have access to that hardware's full specs (not to mention the hardware itself), and 3. to have way, way more free time than I do.

I wish I could help, but I'm afraid you're knocking on the wrong door here. In the wrong street. And probably the wrong town as well. :)

I looked around briefly and it appears that someone is implementing a driver that supports your hardware: https://github.com/lwfinger/rtlwifi_new. Have you tried that one?
