### ISSUE TITLE
Possible memory leakage

### ISSUE THREAD

**Issue by bigeagle** [pvaret/rtl8192cu-fixes#85]
Hi there,

I'm working with a 8192cu chip device (BPi-R1) and hostapd. Thanks for this module, it works on kernel 4.4.10.

However, when I tried to download some large file or linked for a while, wlan0 cannot send anything more, and hostapd reports 

```
hostapd[2116]: +rtl871x_send_eapol
hostapd[2116]: l2_packet_send - send: No buffer space available
```

I found that this should be a driver issue, instead of hostapd. And possibly there's memory leakage somewhere in this module.

I was wondering if you can offer help debugging this.

Cheers,
Justin

**Comment by pvaret** [comment]
Hi,

Sorry for the late update. This repository is only a port of Realtek's own driver to recent kernel, so is not really the right place for in-depth debugging of that driver. Sadly Realtek themselves have not been very responsive about bug reports. You may still want to try your luck with them.

That said, I'm not convinced the bug is in this driver because no one else has been reporting anything similar. At any rate, I would probably recommend switching to the new rtl8xxxu driver in the mainline kernel whenever possible. It's actively maintained and has been improving steadily. I switch to it myself, and beside some power management issues in NetworkManager that were thankfully easy to solve, I'm happy with it.
